name: DFC
favicon: null
layout_spectrum: 0.8775994086172432
typography_spectrum: 0.44762066192924976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5424165143631399
  lightness: 0.47629452450200915
  saturation: 0.35896784579381347
  rhythmicContrast: 0.4639416497666389
purpose: []
