name: DFC
favicon: null
layout_spectrum: 0.8775994086172432
typography_spectrum: 0.44762066192924976
title: DFC - Votre partenaire Champagne
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
